# https://github.com/external-secrets/kubernetes-external-secrets
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - git:
        repoURL: https://github.com/jenana-devops/argocd-ojt-project.git
        revision: HEAD
        files:
          - path: "env/addons/*/*.json"

  template:
    metadata:
      name: "external-secrets-{{cluster.name}}"
      labels:
        group: addons
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: notification

    spec:
      project: addons
      destination:
        name: "{{cluster.name}}"  
        namespace: my-addons
      source:
        repoURL: https://external-secrets.github.io/kubernetes-external-secrets
        targetRevision: "8.5.4"
        chart: kubernetes-external-secrets
        helm:
          values: |-
            fullnameOverride: external-secrets

            crds:
              create: true

            env:
              AWS_REGION: "{{aws_region}}"
              POLLER_INTERVAL_MILLISECONDS: 300000

            securityContext:
              runAsNonRoot: true
              fsGroup: 65534
              
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true